### ISSUE TITLE
NoClassDefFoundError on 1.12.2

### ISSUE THREAD

**Issue by cyruscook** [DarkStorm652/Minecraft-GUI-API#17]
Hi, I'm not sure if you're interested in maintaining this project, however at the moment when packaging this with for 1.12.2 I'm getting a java.lang.NoClassDefFoundError: org/newdawn/slick/SlickException error at org.darkstorm.minecraft.gui.theme.simple.SimpleTheme.<init>(SimpleTheme.java:14).

I'm pretty sure it's to do with this code at UnicodeFontRenderer.java (Line 25)
```Java
try {
	font.loadGlyphs();
} catch(SlickException exception) {
	throw new RuntimeException(exception);
}
```

I'd appreciate any help?

**Comment by cyruscook** [comment]
If anyone else is having this issue, here is a workaround.

Go to org.darkstorm.minecraft.gui.theme.simple.SimpleTheme.java and replace
```Java
fontRenderer = new UnicodeFontRenderer(new Font("Trebuchet MS", Font.PLAIN, 15));
```
with:
```Java
fontRenderer = Minecraft.getMinecraft().fontRendererObj;
```

This isn't perfect as it means that the fancy font the GUI was using will be replaced with the default minecraft font, however at least it works.

**Comment by Frontear** [comment]
Or you could just read the README and use slick2d library. Either works.

**Comment by cyruscook** [comment]
Was using slick2d @Frontear

**Comment by Frontear** [comment]
According to your own comment `java.lang.NoClassDefFoundError: org/newdawn/slick/SlickException error at org.darkstorm.minecraft.gui.theme.simple.SimpleTheme.(SimpleTheme.java:14).` no, you are not. Did you properly link it as a library? If you did, Java should have been able to find the class.

That, or you used a version which didn't contain certain classes.

**Comment by cyruscook** [comment]
Probably was a problem with eclipse linking the library, although I would’ve expected more errors for all the other slick2d implementations
